export const CONFIG_DB_URL = 'TARGET_DB_URL';
export const CONFIG_DB_DIALECT = 'TARGET_DB_DIALECT';
export const CONFIG_LOGS_PATH = 'TARGET_LOGS_PATH';
export const CONFIG_DOMAIN = 'TARGET_DOMAIN';
export const CONFIG_MIDDLEWARE_DOMAIN = 'TARGET_MIDDLEWARE_DOMAIN';
export const CONFIG_SERVER_PORT = 'TARGET_SERVER_PORT';
export const CONFIG_TELEGRAM_BOT_TOKEN = 'TARGET_TELEGRAM_BOT_TOKEN';
export const CONFIG_TELEGRAM_BOT_ADMIN = 'TARGET_TELEGRAM_BOT_ADMIN';
